@extends('layouts.app')
@section('title', 'Tipos Procesos')
@section('page_title', 'Gestión de Tipos de Procesos')
@section('breadcrumb')<li class="breadcrumb-item active">Configuraciones</li><li class="breadcrumb-item active">Tipos Procesos</li>@endsection
@section('content')
<div class="row"><div class="col-12"><div class="card"><div class="card-header d-flex justify-content-between align-items-center"><h3 class="card-title">Lista de Tipos de Procesos</h3><a href="{{ route('internal.tipos-procesos.create') }}" class="btn btn-primary-pro"><i class="fas fa-plus mr-2"></i> Nuevo</a></div><div class="card-body p-0">@if($tipoProcesos && count($tipoProcesos) > 0)<table class="table-crud w-100"><thead><tr><th>Descripción</th><th>Creado</th><th style="width: 120px;">Acciones</th></tr></thead><tbody>@foreach($tipoProcesos as $item)<tr onclick="window.location.href='{{ route('internal.tipos-procesos.show', $item->id ?? 1) }}'" style="cursor: pointer;"><td><strong>{{ $item->descripcion ?? '' }}</strong></td><td>{{ $item->created_at ?? '' }}</td><td onclick="event.stopPropagation();"><div class="action-buttons"><a href="{{ route('internal.tipos-procesos.show', $item->id ?? 1) }}" class="btn-action btn-show" title="Ver"><i class="fas fa-eye"></i></a><a href="{{ route('internal.tipos-procesos.edit', $item->id ?? 1) }}" class="btn-action btn-edit" title="Editar"><i class="fas fa-pencil-alt"></i></a><button type="button" class="btn-action btn-delete" title="Eliminar" onclick="confirmDelete('{{ route('internal.tipos-procesos.destroy', $item->id ?? 1) }}')"><i class="fas fa-trash"></i></button></div></td></tr>@endforeach</tbody></table>@else<div class="empty-state"><i class="fas fa-inbox"></i><p class="mt-3">No hay registros</p><a href="{{ route('internal.tipos-procesos.create') }}" class="btn btn-primary-pro mt-3"><i class="fas fa-plus mr-2"></i> Crear</a></div>@endif</div></div></div></div>
<div class="modal fade" id="deleteModal" tabindex="-1"><div class="modal-dialog modal-sm"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Confirmar eliminación</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body">¿Deseas eliminar este registro?</div><div class="modal-footer"><button type="button" class="btn btn-secondary-pro" data-dismiss="modal">Cancelar</button><form id="deleteForm" method="POST" style="display: inline;">@csrf @method('DELETE')<button type="submit" class="btn btn-danger-pro">Eliminar</button></form></div></div></div></div>
@endsection
@section('scripts')<script>function confirmDelete(url) { document.getElementById('deleteForm').action = url; $('#deleteModal').modal('show'); }</script>@endsection
